### ISSUE TITLE
Add member for getting the displayed path?

### ISSUE THREAD

**Issue by martonmiklos** [Skycoder42/QPathEdit#3]
Hello @Skycoder42 

I have recently came across an issue in my software utilizing QPathEdit. I load/save the UI elements state through QSettings. When loading the UI settings I call setPath() with allowInvalid argument set to true and I use the path() method when saving the GUI state. 

However if the path is not valid (for e.g. the network drive was not available when I loaded the settings) the QPathEdit displays the path with red but when I save the settings with QPathEdit::path() I got an empty string back.

I would either suggest adding a method for querying the displayed path or we could add a bool queryInvalid argument to the path() member (and set to false by default to not to change the current behavior).

What do you think about this?

**Comment by Skycoder42** [comment]
I totally agree with you. I would suggest a method like this: `QString QPathEdit::path(bool *pathValid = nullptr) const`. Feel free to create a pull request with that change if you want to get it done quickly.

**Comment by martonmiklos** [comment]
Ok, but what is the point behind the pointer argument type? The validity of the returned path could be checked by checking the emptiness of the returned path or the ` bool hasAcceptableInput()` method could be used for this purpose as well.

**Comment by Skycoder42** [comment]
You do have a point. I also just realised that this would change the way the `path` property would behave, and I would like to avoid that.

So instead, we could either:
1. Change the method to take an optional argument, as already suggested by you: `QString QPathEdit::path(bool queryInvalid = false) const`. This would not change default behaviour, since the argument is defaulted.
2. Add a new method for this purpouse: `QString QPathEdit::editPath() const`. This would return the path as currently visible in the text edit, no matter it's validity.

I personally would prefer the 2. variant, as we could keep binary compability this way. Also I personally think having two seperate methods makes it clearer how the result of the two could differ.

**Comment by martonmiklos** [comment]
I prefer the 2. variant too, PR submitted.
